package org.freedomwave.domain.model

import org.freedomwave.data.api.dto.HostDto

data class Host(
    val uuid: String,
    val remark: String,
    val address: String,
    val port: Int,
    val path: String?,
    val sni: String?,
    val host: String?,
    val alpn: String?,
    val fingerprint: String?,
    val isDisabled: Boolean,
    val isHidden: Boolean,
    val securityLayer: String,
    val tags: List<String>,
    val serverDescription: String?,
    val pinnedPeerCertSha256: String?,
    val verifyPeerCertByName: String?,
    val mihomoIpVersion: String?,
    val overrideSniFromAddress: Boolean,
    val keepSniBlank: Boolean,
    val shuffleHost: Boolean,
    val mihomoX25519: Boolean,
    val nodes: List<String>,
    val configProfileUuid: String?,
    val configProfileInboundUuid: String?,
    val vlessRouteId: Int?,
    val xrayJsonTemplateUuid: String?,
) {
    companion object {
        fun from(dto: HostDto) = Host(
            uuid                     = dto.uuid,
            remark                   = dto.remark,
            address                  = dto.address,
            port                     = dto.port,
            path                     = dto.path,
            sni                      = dto.sni,
            host                     = dto.host,
            alpn                     = dto.alpn,
            fingerprint              = dto.fingerprint,
            isDisabled               = dto.isDisabled,
            isHidden                 = dto.isHidden,
            securityLayer            = dto.securityLayer,
            tags                     = dto.tags,
            serverDescription        = dto.serverDescription,
            pinnedPeerCertSha256     = dto.pinnedPeerCertSha256,
            verifyPeerCertByName     = dto.verifyPeerCertByName,
            mihomoIpVersion          = dto.mihomoIpVersion,
            overrideSniFromAddress   = dto.overrideSniFromAddress,
            keepSniBlank             = dto.keepSniBlank,
            shuffleHost              = dto.shuffleHost,
            mihomoX25519             = dto.mihomoX25519,
            nodes                    = dto.nodes,
            configProfileUuid        = dto.inbound?.configProfileUuid,
            configProfileInboundUuid = dto.inbound?.configProfileInboundUuid,
            vlessRouteId             = dto.vlessRouteId,
            xrayJsonTemplateUuid     = dto.xrayJsonTemplateUuid,
        )
    }
}
