package art.yniyniyni.freedomwave.ui.feature.nodes

/** ISO-3166 alpha-2 code + English name. `XX` is the "Unknown" sentinel the backend defaults to. */
data class Country(val code: String, val name: String)

val countries: List<Country> = listOf(
    Country("XX", "Unknown"),
    Country("AD", "Andorra"), Country("AE", "United Arab Emirates"), Country("AF", "Afghanistan"),
    Country("AG", "Antigua and Barbuda"), Country("AI", "Anguilla"), Country("AL", "Albania"),
    Country("AM", "Armenia"), Country("AO", "Angola"), Country("AR", "Argentina"),
    Country("AT", "Austria"), Country("AU", "Australia"), Country("AW", "Aruba"),
    Country("AZ", "Azerbaijan"), Country("BA", "Bosnia and Herzegovina"), Country("BB", "Barbados"),
    Country("BD", "Bangladesh"), Country("BE", "Belgium"), Country("BF", "Burkina Faso"),
    Country("BG", "Bulgaria"), Country("BH", "Bahrain"), Country("BI", "Burundi"),
    Country("BJ", "Benin"), Country("BN", "Brunei"), Country("BO", "Bolivia"),
    Country("BR", "Brazil"), Country("BS", "Bahamas"), Country("BT", "Bhutan"),
    Country("BW", "Botswana"), Country("BY", "Belarus"), Country("BZ", "Belize"),
    Country("CA", "Canada"), Country("CD", "DR Congo"), Country("CF", "Central African Republic"),
    Country("CG", "Congo"), Country("CH", "Switzerland"), Country("CI", "Côte d'Ivoire"),
    Country("CL", "Chile"), Country("CM", "Cameroon"), Country("CN", "China"),
    Country("CO", "Colombia"), Country("CR", "Costa Rica"), Country("CU", "Cuba"),
    Country("CV", "Cape Verde"), Country("CY", "Cyprus"), Country("CZ", "Czechia"),
    Country("DE", "Germany"), Country("DJ", "Djibouti"), Country("DK", "Denmark"),
    Country("DM", "Dominica"), Country("DO", "Dominican Republic"), Country("DZ", "Algeria"),
    Country("EC", "Ecuador"), Country("EE", "Estonia"), Country("EG", "Egypt"),
    Country("ER", "Eritrea"), Country("ES", "Spain"), Country("ET", "Ethiopia"),
    Country("FI", "Finland"), Country("FJ", "Fiji"), Country("FM", "Micronesia"),
    Country("FR", "France"), Country("GA", "Gabon"), Country("GB", "United Kingdom"),
    Country("GD", "Grenada"), Country("GE", "Georgia"), Country("GH", "Ghana"),
    Country("GM", "Gambia"), Country("GN", "Guinea"), Country("GQ", "Equatorial Guinea"),
    Country("GR", "Greece"), Country("GT", "Guatemala"), Country("GW", "Guinea-Bissau"),
    Country("GY", "Guyana"), Country("HK", "Hong Kong"), Country("HN", "Honduras"),
    Country("HR", "Croatia"), Country("HT", "Haiti"), Country("HU", "Hungary"),
    Country("ID", "Indonesia"), Country("IE", "Ireland"), Country("IL", "Israel"),
    Country("IN", "India"), Country("IQ", "Iraq"), Country("IR", "Iran"),
    Country("IS", "Iceland"), Country("IT", "Italy"), Country("JM", "Jamaica"),
    Country("JO", "Jordan"), Country("JP", "Japan"), Country("KE", "Kenya"),
    Country("KG", "Kyrgyzstan"), Country("KH", "Cambodia"), Country("KI", "Kiribati"),
    Country("KM", "Comoros"), Country("KN", "Saint Kitts and Nevis"), Country("KP", "North Korea"),
    Country("KR", "South Korea"), Country("KW", "Kuwait"), Country("KZ", "Kazakhstan"),
    Country("LA", "Laos"), Country("LB", "Lebanon"), Country("LC", "Saint Lucia"),
    Country("LI", "Liechtenstein"), Country("LK", "Sri Lanka"), Country("LR", "Liberia"),
    Country("LS", "Lesotho"), Country("LT", "Lithuania"), Country("LU", "Luxembourg"),
    Country("LV", "Latvia"), Country("LY", "Libya"), Country("MA", "Morocco"),
    Country("MC", "Monaco"), Country("MD", "Moldova"), Country("ME", "Montenegro"),
    Country("MG", "Madagascar"), Country("MH", "Marshall Islands"), Country("MK", "North Macedonia"),
    Country("ML", "Mali"), Country("MM", "Myanmar"), Country("MN", "Mongolia"),
    Country("MR", "Mauritania"), Country("MT", "Malta"), Country("MU", "Mauritius"),
    Country("MV", "Maldives"), Country("MW", "Malawi"), Country("MX", "Mexico"),
    Country("MY", "Malaysia"), Country("MZ", "Mozambique"), Country("NA", "Namibia"),
    Country("NE", "Niger"), Country("NG", "Nigeria"), Country("NI", "Nicaragua"),
    Country("NL", "Netherlands"), Country("NO", "Norway"), Country("NP", "Nepal"),
    Country("NR", "Nauru"), Country("NZ", "New Zealand"), Country("OM", "Oman"),
    Country("PA", "Panama"), Country("PE", "Peru"), Country("PG", "Papua New Guinea"),
    Country("PH", "Philippines"), Country("PK", "Pakistan"), Country("PL", "Poland"),
    Country("PT", "Portugal"), Country("PW", "Palau"), Country("PY", "Paraguay"),
    Country("QA", "Qatar"), Country("RO", "Romania"), Country("RS", "Serbia"),
    Country("RU", "Russia"), Country("RW", "Rwanda"), Country("SA", "Saudi Arabia"),
    Country("SB", "Solomon Islands"), Country("SC", "Seychelles"), Country("SD", "Sudan"),
    Country("SE", "Sweden"), Country("SG", "Singapore"), Country("SI", "Slovenia"),
    Country("SK", "Slovakia"), Country("SL", "Sierra Leone"), Country("SM", "San Marino"),
    Country("SN", "Senegal"), Country("SO", "Somalia"), Country("SR", "Suriname"),
    Country("SS", "South Sudan"), Country("ST", "São Tomé and Príncipe"), Country("SV", "El Salvador"),
    Country("SY", "Syria"), Country("SZ", "Eswatini"), Country("TD", "Chad"),
    Country("TG", "Togo"), Country("TH", "Thailand"), Country("TJ", "Tajikistan"),
    Country("TL", "Timor-Leste"), Country("TM", "Turkmenistan"), Country("TN", "Tunisia"),
    Country("TO", "Tonga"), Country("TR", "Turkey"), Country("TT", "Trinidad and Tobago"),
    Country("TV", "Tuvalu"), Country("TW", "Taiwan"), Country("TZ", "Tanzania"),
    Country("UA", "Ukraine"), Country("UG", "Uganda"), Country("US", "United States"),
    Country("UY", "Uruguay"), Country("UZ", "Uzbekistan"), Country("VA", "Vatican City"),
    Country("VC", "Saint Vincent and the Grenadines"), Country("VE", "Venezuela"), Country("VN", "Vietnam"),
    Country("VU", "Vanuatu"), Country("WS", "Samoa"), Country("YE", "Yemen"),
    Country("ZA", "South Africa"), Country("ZM", "Zambia"), Country("ZW", "Zimbabwe"),
)

private val countryByCode: Map<String, Country> = countries.associateBy { it.code }

fun countryFor(code: String): Country =
    countryByCode[code.uppercase()] ?: Country(code.uppercase(), code.uppercase())
